[16859]:[filesystem] sdcardfs: fs: Export vfs_rmdir2
Plan: sdcardfs: fs: Export vfs_rmdir2
Type: PATCH
Test: No need to test
Note: Reference patch
      https://android.googlesource.com/kernel/common/+/4c7fc336f6e3ec34af2c6931fce4d496f560da90%5E%21/#F0

ANDROID: fs: Export vfs_rmdir2

allmodconfig builds fail with

ERROR: "vfs_rmdir2" undefined!

Export the missing function.

Fixes: f9cb61dcb00c ("ANDROID: sdcardfs: User new permission2 functions")

Change-Id: Id899560a5e6484581fb36e66d5c8c8a63349b762