[16859]:[filesystem] sdcardfs: fs: Export free_fs_struct and set_fs_pwd
Plan: sdcardfs: fs: Export free_fs_struct and set_fs_pwd
Type: PATCH
Test: No need to test
Note: Reference patch
      https://android.googlesource.com/kernel/common/+/1cd3d347147bee1b8a3fb7624ab23eb3bdcece41%5E%21/#F0

ANDROID: fs: Export free_fs_struct and set_fs_pwd

allmodconfig builds fail with:

ERROR: "free_fs_struct" undefined!
ERROR: "set_fs_pwd" undefined!

Export the missing symbols.

Fixes: 0ec03f845799 ("ANDROID: sdcardfs: override umask on mkdir and create")

Change-Id: I068eb5b4ff0ff0eecd2ee5a89a6c1ff7f888f063