Merge remote-tracking branch 'qcom/lineage-20' into lineage-20
Squashed commit of the following:

commit 35e547e3394b364e34b4fc293de21adbbbc6b2de
Author: Alexander Grund <flamefire89@gmail.com>
Date:   Tue Oct 31 16:25:09 2023 +0100

    sched/walt: Add missing WALT call to `dequeue_task_fair`

    Similar to `dec_cfs_rq_hmp_stats` vs `walt_dec_cfs_cumulative_runnable_avg`
    we need to call `walt_dec_cumulative_runnable_avg` where `dec_rq_hmp_stats`
    is called.
    Corresponds to the `walt_inc_cfs_cumulative_runnable_avg` call in `enqueue_task_fair`.

    Based on 4e29a6c5f98f9694d5ad01a4e7899aad157f8d49 ("sched: Add missing WALT code")
    Fixes c0fa7577022c4169e1aaaf1bd9e04f63d285beb2 ("sched/walt: Re-add code to allow WALT to function")

    Change-Id: If2b291e1e509ba300d7f4b698afe73a72b273604

commit 445ebe52b249be196978c9959c467996b7b46e35
Author: Jaegeuk Kim <jaegeuk@google.com>
Date:   Tue Oct 1 22:28:02 2019 -0700

    ICE, pfk: fix to set dio_inode precisely

    When using loopback device with dio, we can't rely on page flag.

    Bug: 141601405
    Bug: 141860559
    Bug: 140882488
    Change-Id: I09526c25e8d5333853e777f29333f9fa8da37459
    Signed-off-by: Jaegeuk Kim <jaegeuk@google.com>

commit 420c7da5ec99f942f2f7b77fdbd9059044f626e4
Author: Brenden Blanco <bblanco@plumgrid.com>
Date:   Tue Jul 19 12:16:48 2016 -0700

    net: add ndo to setup/query xdp prog in adapter rx

    Add one new netdev op for drivers implementing the BPF_PROG_TYPE_XDP
    filter. The single op is used for both setup/query of the xdp program,
    modelled after ndo_setup_tc.

    Change-Id: Ie46dec0b47e417e97d5fed19d7f2b143eab4ea73
    Signed-off-by: Brenden Blanco <bblanco@plumgrid.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit f55efe5b761076743338418a1f888cb4ef2ff137
Author: Paolo Abeni <pabeni@redhat.com>
Date:   Fri Feb 26 10:45:37 2016 +0100

    netdev: introduce ndo_set_rx_headroom

    This method allows the controlling device (i.e. the bridge) to specify
    additional headroom to be allocated for skb head on frame reception.

    Change-Id: Ic4938a247408a87538a11c45e3fbc2031f4ac832
    Signed-off-by: Paolo Abeni <pabeni@redhat.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 04a3e74655c1e55899196636abf65c39ef984ccc
Author: Keller, Jacob E <jacob.e.keller@intel.com>
Date:   Mon Feb 8 16:05:03 2016 -0800

    ethtool: correctly ensure {GS}CHANNELS doesn't conflict with GS{RXFH}

    Ethernet drivers implementing both {GS}RXFH and {GS}CHANNELS ethtool ops
    incorrectly allow SCHANNELS when it would conflict with the settings
    from SRXFH. This occurs because it is not possible for drivers to
    understand whether their Rx flow indirection table has been configured
    or is in the default state. In addition, drivers currently behave in
    various ways when increasing the number of Rx channels.

    Some drivers will always destroy the Rx flow indirection table when this
    occurs, whether it has been set by the user or not. Other drivers will
    attempt to preserve the table even if the user has never modified it
    from the default driver settings. Neither of these situation is
    desirable because it leads to unexpected behavior or loss of user
    configuration.

    The correct behavior is to simply return -EINVAL when SCHANNELS would
    conflict with the current Rx flow table settings. However, it should
    only do so if the current settings were modified by the user. If we
    required that the new settings never conflict with the current (default)
    Rx flow settings, we would force users to first reduce their Rx flow
    settings and then reduce the number of Rx channels.

    This patch proposes a solution implemented in net/core/ethtool.c which
    ensures that all drivers behave correctly. It checks whether the RXFH
    table has been configured to non-default settings, and stores this
    information in a private netdev flag. When the number of channels is
    requested to change, it first ensures that the current Rx flow table is
    not going to assign flows to now disabled channels.

    Change-Id: I3c7ecdeed66e20a423fd46a0ebc937020e951105
    Signed-off-by: Jacob Keller <jacob.e.keller@intel.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 1a9554dcfe45043684ef68d863fa83cd0f01aaa1
Author: Jiri Pirko <jiri@mellanox.com>
Date:   Fri Dec 4 15:01:31 2015 +0100

    net: constify netif_is_* helpers net_device param

    As suggested by Eric, these helpers should have const dev param.

    Suggested-by: Eric Dumazet <eric.dumazet@gmail.com>
    Change-Id: I320e01f441a2b266680cdaefc5eb659f329143fb
    Signed-off-by: Jiri Pirko <jiri@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit ee3368dcece947566148d1fc08389dec18d4fd59
Author: Jiri Pirko <jiri@mellanox.com>
Date:   Thu Dec 3 12:12:09 2015 +0100

    net: add netif_is_lag_port helper

    Some code does not mind if a device is bond slave or team port and treats
    them the same, as generic LAG ports.

    Change-Id: I9f1940897da8079deaec8d59bfba5e8a2c91c230
    Signed-off-by: Jiri Pirko <jiri@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 580956808514afa6de2949f1e916105683b9a9c4
Author: Jiri Pirko <jiri@mellanox.com>
Date:   Thu Dec 3 12:12:08 2015 +0100

    net: add netif_is_lag_master helper

    Some code does not mind if the master is bond or team and treats them
    the same, as generic LAG.

    Change-Id: I97803f67bdaf42a2cbf3eb6adf417c1aeebb5be1
    Signed-off-by: Jiri Pirko <jiri@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 7746abf2d00e88b99a783e5c2e95a5a4fd72333a
Author: Jiri Pirko <jiri@mellanox.com>
Date:   Thu Dec 3 12:12:07 2015 +0100

    net: add netif_is_team_port helper

    Similar to other helpers, caller can use this to find out if device is
    team port.

    Change-Id: Id39d3c7a188de21768a4f18190e25f27e5846b28
    Signed-off-by: Jiri Pirko <jiri@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit b4345574869f518fca63b0277f166b4aba9c27db
Author: Jiri Pirko <jiri@mellanox.com>
Date:   Thu Dec 3 12:12:06 2015 +0100

    net: add netif_is_team_master helper

    Similar to other helpers, caller can use this to find out if device is
    team master.

    Change-Id: I8301442073b4af1e19a1ee207fa5055a3ab5c908
    Signed-off-by: Jiri Pirko <jiri@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 04cf2352eea8c701a74bb0a7701e581657d43cf1
Author: siimsek <malisimsek17@gmail.com>
Date:   Sun Sep 18 03:24:02 2022 -0400

    ASoC: wcd_cpe: Fix enum-conversion warnings

    sound/soc/codecs/wcd_cpe_services.c:667:17: error: implicit
    conversion from enumeration type 'enum cpe_svc_result' to different
    enumeration type 'enum cmi_api_result' [-Werror,-Wenum-conversion]
            notif.result = result;
                         ~ ^~~~~~
    sound/soc/codecs/wcd_cpe_services.c:1358:8: error: implicit
    conversion from enumeration type 'enum cpe_svc_result' to different
    enumeration type 'enum cpe_process_result' [-Werror,-Wenum-conversion]
                    rc = cpe_send_msg_to_inbox(t_info, 0, m);
                       ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 errors generated.

    Change-Id: Ib9fce60017066e9c96e79195d7dba9ffb9177148

commit fb68c2437a1bf79d5df5db66a7716ca1707a4f07
Author: Nathan Chancellor <natechancellor@gmail.com>
Date:   Sat Apr 7 12:16:19 2018 -0700

    icnss: Fix enum-conversion warning from Clang

    ../drivers/soc/qcom/icnss.c:3418:37: warning: implicit conversion from
    enumeration type 'enum icnss_driver_mode' to different enumeration type
    'enum wlfw_driver_mode_enum_v01' [-Wenum-conversion]
            ret = wlfw_wlan_mode_send_sync_msg(mode);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~
    1 warning generated.

    Change-Id: I7ff0326411b4b2a6e020cf50bc655ec26c1e4992
    Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

commit 2be15e8bb539bedb55fc4361a2256b5150190634
Author: Georg Veichtlbauer <georg@vware.at>
Date:   Thu Nov 2 09:41:07 2023 +0100

    ipa_v2: Fix enum conversion warnings

    Change-Id: I70ebba2c049700cebd94a23df33cb2efbb588875

commit 38833e6569e81c55c72466c18b2918f8cd76e1f9
Author: vantoman <Mustafa.vantom@gmail.com>
Date:   Sun Jun 4 13:39:51 2023 +0200

    ipa_v3: Fix enum conversion warnings

    clang-15 complains:
    drivers/platform/msm/ipa/ipa_v3/rmnet_ipa.c:457:41: error: implicit
    conversion from enumeration type 'enum ipa_ip_type_enum_v01'
    to different enumeration type 'enum ipa_ip_type'
    [-Werror,-Wenum-conversion]
            q6_ul_flt_rule_ptr->ip = flt_spec_ptr->ip_type;
                                   ~ ~~~~~~~~~~~~~~^~~~~~~
    drivers/platform/msm/ipa/ipa_v3/rmnet_ipa.c:459:45: error: implicit
    conversion from enumeration type 'enum ipa_filter_action_enum_v01'
    to different enumeration type 'enum ipa_flt_action'
    [-Werror,-Wenum-conversion]
            q6_ul_flt_rule_ptr->action = flt_spec_ptr->filter_action;
                                       ~ ~~~~~~~~~~~~~~^~~~~~~~~~~~~
    2 errors generated.

    Change-Id: I7a40b0d7b082836670b6551f2a04aa141d240153

commit 3261ee8bbcf9314d2209af409d31fec5241539fb
Author: Miklos Szeredi <mszeredi@redhat.com>
Date:   Tue Sep 27 11:03:57 2016 +0200

    libfs: support RENAME_NOREPLACE in simple_rename()

    This is trivial to do:

     - add flags argument to simple_rename()
     - check if flags doesn't have any other than RENAME_NOREPLACE
     - assign simple_rename() to .rename2 instead of .rename

    Filesystems converted:

    hugetlbfs, ramfs, bpf.

    Debugfs uses simple_rename() to implement debugfs_rename(), which is for
    debugfs instances to rename files internally, not for userspace filesystem
    access.  For this case pass zero flags to simple_rename().

    Change-Id: I1a46ece3b40b05c9f18fd13b98062d2a959b76a0
    Signed-off-by: Miklos Szeredi <mszeredi@redhat.com>
    Acked-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
    Cc: Alexei Starovoitov <ast@kernel.org>

commit 78a6bccb2dae3abb2a2ae3509fb7c67951af58a4
Author: LuK1337 <priv.luk@gmail.com>
Date:   Fri Oct 27 18:51:43 2023 +0200

    qcacld-3.0: Fix strict-prototypes error

    Change-Id: Ifb8fe11c1d647ab1286e9bb0a63ee0c83641f9a8

commit 205fa7f309398d49010b9951c8b0b2179de0e604
Author: jianil <quic_jianil@quicinc.com>
Date:   Mon Dec 19 10:58:35 2022 -0800

    qcacld-3.0: Fix compile error of mdie

    Fix compile error of mdie[SIR_MDIE_SIZE], use
    mdie[] instead.

    Change-Id: I934d3f02a19b511583141deeca7af5b4d4c0ef30
    CRs-Fixed: 3364146

commit 8a021c2fe1db1b3a376a563d0156e9488d9f5aff
Author: LuK1337 <priv.luk@gmail.com>
Date:   Fri Oct 27 18:44:20 2023 +0200

    writeback: Fix cgroup_path() return value check

    cgroup_path() returns length, not char *.

    Change-Id: I8bdfcc0fc58789aa23f730866f27fbb932b24be1

commit 4fe3806e879f03eb0d52cfa4e88d642bb8671d7a
Author: LuK1337 <priv.luk@gmail.com>
Date:   Fri Oct 27 18:14:31 2023 +0200

    msm: diag: Fix strict-prototypes error

    Change-Id: I1b61a6df9d028fdff86bca6c6f3642a050e8f005

commit e93ed3fb56d3c45f808e020c0e03587c9a227b7b
Author: LuK1337 <priv.luk@gmail.com>
Date:   Fri Oct 27 18:14:10 2023 +0200

    msm: camera: Fix strict-prototypes error

    Change-Id: Iedf64ccf3ab2364a5d1ba04469afd89be010e835

commit 217eb640f102fe9e0ac99f3ee242d2d96ee54817
Author: LuK1337 <priv.luk@gmail.com>
Date:   Fri Oct 27 18:13:51 2023 +0200

    msm: vidc: Fix strict-prototypes error

    Change-Id: I5e80493d5c7600ecdafc0b78e2c72be27095fae0

commit d01bc377dc0c8d1a759a302b8742ba5aa7e0aba9
Author: LuK1337 <priv.luk@gmail.com>
Date:   Fri Oct 27 18:13:27 2023 +0200

    msm: msm_bus: Fix strict-prototypes error

    Change-Id: I756cfd498312be1ecc264576af8c874c89d93813

commit 14ee0e92043f0b6f2ef611c9494a91287e414608
Author: LuK1337 <priv.luk@gmail.com>
Date:   Fri Oct 27 18:13:02 2023 +0200

    msm: qdsp6v2: Fix strict-prototypes error

    Change-Id: I55fbab53a24e395a6f34c699d5b55ad38d023c24

commit dd212eea77d96b49ee94e8a5290e4153315ebbde
Author: LuK1337 <priv.luk@gmail.com>
Date:   Fri Oct 27 18:12:23 2023 +0200

    msm: thermal-dev: Fix strict-prototypes error

    Change-Id: If0e72ed9ae5ac9ea2db67f92e34dbf9675049d26

commit 0a15a8978fd7e9f9e8a0ca01c47088e81ba7c319
Author: LuK1337 <priv.luk@gmail.com>
Date:   Fri Oct 27 18:11:09 2023 +0200

    msm: mdss: Fix strict-prototypes error

    Change-Id: I59c35db0bbf8d15e8b814ae7b729c8301ac4ed97

commit 18eca50308f818a5a812c7445497b35b97084cd0
Author: Bruno Martins <bgcngm@gmail.com>
Date:   Fri Oct 20 23:29:59 2023 +0100

    arm64: vdso32: Allow building with LLVM integrated AS

    Change-Id: I8bfc0e53b4bd347adaa298594402a2210aed3b49

commit 7c473173dd2bad7ab914693da6df3f4c236678c4
Author: Nick Desaulniers <ndesaulniers@google.com>
Date:   Tue Oct 19 15:36:45 2021 -0700

    arm64: vdso32: suppress error message for 'make mrproper'

    commit 14831fad73f5ac30ac61760487d95a538e6ab3cb upstream.

    When running the following command without arm-linux-gnueabi-gcc in
    one's $PATH, the following warning is observed:

    $ ARCH=arm64 CROSS_COMPILE_COMPAT=arm-linux-gnueabi- make -j72 LLVM=1 mrproper
    make[1]: arm-linux-gnueabi-gcc: No such file or directory

    This is because KCONFIG is not run for mrproper, so CONFIG_CC_IS_CLANG
    is not set, and we end up eagerly evaluating various variables that try
    to invoke CC_COMPAT.

    This is a similar problem to what was observed in
    commit dc960bfeedb0 ("h8300: suppress error messages for 'make clean'")

    Reported-by: Lucas Henneman <henneman@google.com>
    Suggested-by: Masahiro Yamada <masahiroy@kernel.org>
    Change-Id: I672930f558d087230c119ece518b83cac7d8baa7
    Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
    Reviewed-by: Vincenzo Frascino <vincenzo.frascino@arm.com>
    Reviewed-by: Nathan Chancellor <nathan@kernel.org>
    Tested-by: Nathan Chancellor <nathan@kernel.org>
    Link: https://lore.kernel.org/r/20211019223646.1146945-4-ndesaulniers@google.com
    Signed-off-by: Will Deacon <will@kernel.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit 061b4837b2dd80f4a98f979dd5dcc97643e8513a
Author: Stephen Boyd <swboyd@chromium.org>
Date:   Mon Aug 17 18:49:50 2020 -0700

    ARM64: vdso32: Install vdso32 from vdso_install

    [ Upstream commit 8d75785a814241587802655cc33e384230744f0c ]

    Add the 32-bit vdso Makefile to the vdso_install rule so that 'make
    vdso_install' installs the 32-bit compat vdso when it is compiled.

    Fixes: a7f71a2c8903 ("arm64: compat: Add vDSO")
    Change-Id: I554988049d9f4395d226988a410a0a68eeed304d
    Signed-off-by: Stephen Boyd <swboyd@chromium.org>
    Reviewed-by: Vincenzo Frascino <vincenzo.frascino@arm.com>
    Acked-by: Will Deacon <will@kernel.org>
    Cc: Vincenzo Frascino <vincenzo.frascino@arm.com>
    Link: https://lore.kernel.org/r/20200818014950.42492-1-swboyd@chromium.org
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
    Signed-off-by: Sasha Levin <sashal@kernel.org>

commit 921297f341fcbf16762eade007c9e3456f4881fe
Author: Will Deacon <will@kernel.org>
Date:   Fri Oct 4 15:44:45 2019 +0100

    arm64: vdso32: Don't use KBUILD_CPPFLAGS unconditionally

    KBUILD_CPPFLAGS is defined differently depending on whether the main
    compiler is clang or not. This means that it is not possible to build
    the compat vDSO with GCC if the rest of the kernel is built with clang.

    Define VDSO_CPPFLAGS directly to break this dependency and allow a clang
    kernel to build a compat vDSO with GCC:

      $ make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- \
        CROSS_COMPILE_COMPAT=arm-linux-gnueabihf- CC=clang \
        COMPATCC=arm-linux-gnueabihf-gcc

    Acked-by: Catalin Marinas <catalin.marinas@arm.com>
    Change-Id: Iaa7f6197bc99ca5c8162c6e34e3dd38c31d894cd
    Signed-off-by: Will Deacon <will@kernel.org>

commit 000406a64080997233971f02ae9b81df6a9813f2
Author: Vincenzo Frascino <vincenzo.frascino@arm.com>
Date:   Thu Oct 3 18:48:36 2019 +0100

    arm64: vdso32: Remove jump label config option in Makefile

    The jump labels are not used in vdso32 since it is not possible to run
    runtime patching on them.

    Remove the configuration option from the Makefile.

    Cc: Will Deacon <will@kernel.org>
    Cc: Catalin Marinas <catalin.marinas@arm.com>
    Change-Id: Ie0f311218a761a6b18b3ed3cccf30fd10f440407
    Signed-off-by: Vincenzo Frascino <vincenzo.frascino@arm.com>
    Acked-by: Catalin Marinas <catalin.marinas@arm.com>
    Tested-by: Catalin Marinas <catalin.marinas@arm.com>
    Signed-off-by: Will Deacon <will@kernel.org>

Change-Id: Ic8c8ceb50c72f59a266950008d19b85bc4bbf5dd